import { Product } from '../types';

// The new list of categories based on your request
export const CATEGORIES = [
  "All",
  "Gear Knobs",
  "DRL Lights",
  "Bar Lights",
  "Mobile Holders",
  "Steerings",
  "Dashboard Wax",
  "Dashboard Perfumes",
  "Car Antennas",
  "Mirror Covers",
  "Armrest",
  "Pedal Covers"
];

// Updated Mock Products to match the new Car Accessories theme
export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Crystal LED Gear Knob',
    price: 1250.00,
    category: 'Gear Knobs',
    image: 'https://m.media-amazon.com/images/I/61+6y+xXjOL.jpg',
    description: 'Touch activated LED crystal gear knob with multi-color changing light.',
    rating: 4.8,
    reviews: 120,
    tags: ['interior', 'lighting', 'gear'],
    isUpcoming: true,
  },
  {
    id: '2',
    name: 'Audi Style DRL Tube Lights',
    price: 850.00,
    category: 'DRL Lights',
    image: 'https://m.media-amazon.com/images/I/61S1F1a+tYL._AC_UF1000,1000_QL80_.jpg',
    description: 'Flexible tube DRL lights with matrix indicator function.',
    rating: 4.5,
    reviews: 85,
    tags: ['exterior', 'lights', 'led'],
    isUpcoming: true,
  },
  {
    id: '3',
    name: 'Gravity Car Phone Holder',
    price: 399.00,
    category: 'Mobile Holders',
    image: 'https://m.media-amazon.com/images/I/61J6sL-k2AL.jpg',
    description: 'Auto-lock gravity mounting system for secure phone holding.',
    rating: 4.2,
    reviews: 45,
    tags: ['accessory', 'phone', 'mount'],
    isUpcoming: false,
  },
  {
    id: '4',
    name: 'Sport Racing Steering Wheel',
    price: 3450.00,
    category: 'Steerings',
    image: 'https://m.media-amazon.com/images/I/71F7XyF1iLL.jpg',
    description: '14-inch deep dish racing steering wheel with leather grip.',
    rating: 4.7,
    reviews: 210,
    tags: ['performance', 'interior', 'steering'],
    isUpcoming: false,
  },
  {
    id: '5',
    name: 'Ultimate Dashboard Wax',
    price: 250.00,
    category: 'Dashboard Wax',
    image: 'https://m.media-amazon.com/images/I/71I9-d1i+FL._AC_UF1000,1000_QL80_.jpg',
    description: 'Restores shine and protects against UV rays.',
    rating: 4.6,
    reviews: 32,
    tags: ['cleaning', 'maintenance', 'shine'],
    isUpcoming: false,
  },
  {
    id: '6',
    name: 'Solar Rotating Car Perfume',
    price: 499.00,
    category: 'Dashboard Perfumes',
    image: 'https://m.media-amazon.com/images/I/61g-Rz-G5dL.jpg',
    description: 'Solar powered rotating double ring suspension air freshener.',
    rating: 4.3,
    reviews: 56,
    tags: ['fresh', 'interior', 'scent'],
    isUpcoming: false,
  },
  {
    id: '7',
    name: 'Shark Fin Antenna',
    price: 320.00,
    category: 'Car Antennas',
    image: 'https://m.media-amazon.com/images/I/51M3f+wJqZL.jpg',
    description: 'Universal fit decorative shark fin antenna with signal enhancement.',
    rating: 4.9,
    reviews: 400,
    tags: ['exterior', 'signal', 'style'],
    isUpcoming: false,
  },
  {
    id: '8',
    name: 'Carbon Fiber Mirror Covers',
    price: 950.00,
    category: 'Mirror Covers',
    image: 'https://m.media-amazon.com/images/I/61N+x+u+q+L.jpg',
    description: 'Glossy carbon fiber texture replacement mirror caps.',
    rating: 4.4,
    reviews: 98,
    tags: ['exterior', 'carbon', 'protection'],
    isUpcoming: false,
  },
];